extend utils for examples and skill info
OpenVoiceOS/ovos_skill_manager pull request #100
Opened 2022-11-04 00:45 UTC by AIIX

- Extends utils to provide examples as needed by Homescreen skill, needed by https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/53 
- Extends utils to provide skill info built from skill JSON as needed by https://github.com/NeonGeckoCom/skill-about

2022-11-04 00:52 UTC, NeonDaniel requested changes
Minor change request to prioritize skill.json over readme.md. Should probably add unit tests too, but that could be a separate issue for a follow-up PR

2022-11-04 00:52 UTC, NeonDaniel commented on ovos_skills_manager/utils.py
> +    if path.isfile(path.join(skill_dir, "README.md")):
I think `skill.json` take priority over readme here; it will save on parsing and should be equivalent to what's in the readme anyway

2022-11-04 00:59 UTC, AIIX commented on ovos_skills_manager/utils.py
> +    if path.isfile(path.join(skill_dir, "README.md")):
fixed

2022-11-07 13:19 UTC, builderjer commented on ovos_skills_manager/utils.py
> +def get_skills_examples(randomize=False):
Is there a setting for this somewhere?

2022-11-07 13:30 UTC, AIIX commented on ovos_skills_manager/utils.py
> +def get_skills_examples(randomize=False):
Which setting ? The setting for homescreen is still in homescreen skill, where it controls to use this or not

2022-11-07 13:36 UTC, builderjer commented on ovos_skills_manager/utils.py
> +def get_skills_examples(randomize=False):
A setting to randomize. Is that in the homescreen settings also?

2022-11-07 13:51 UTC, builderjer commented on ovos_skills_manager/utils.py
> +def get_skills_examples(randomize=False):
I see it [here](https://github.com/OpenVoiceOS/skill-ovos-homescreen/blob/bbe52c7bc3bae4e47e4ace2eaa810572c34cba8e/__init__.py#L182) but can you change it with the settings? I will make a PR in homescreen to do so

2022-11-07 13:53 UTC, merged