Add method to install skill via URL without SkillEntry/Appstore parsing
OpenVoiceOS/ovos_skill_manager pull request #33
Opened 2021-06-11 19:43 UTC by NeonDaniel

Closes #30
Add method to install skill from URL (bypass search and most SkillEntry parsing)
Add helper method get_skill_entry_from_url to build a minimal SkillEntry from a github url
Add unit tests for added helper method

2021-06-11 20:25 UTC, JarbasAl commented on ovos_skills_manager/github/utils.py
> +    from ovos_skills_manager.skill_entry import SkillEntry
having these imports here makes me think we should move the method elsewhere, cyclic imports are usually not good... any suggestions for other location ?

2021-06-11 20:42 UTC, NeonDaniel commented on ovos_skills_manager/github/utils.py
> +    from ovos_skills_manager.skill_entry import SkillEntry
This could move to `github` module directly; `SkillEntry` would be the only needed import then..

2021-06-11 21:01 UTC, JarbasAl commented on ovos_skills_manager/github/utils.py
> +    from ovos_skills_manager.skill_entry import SkillEntry
in general i dont think a SkillEntry object should exist in the github module at all....
 github module really should only use requests and little else
 
 why not directly in the osm module? feels lie it could even be a class method?

2021-06-11 21:12 UTC, NeonDaniel commented on ovos_skills_manager/github/utils.py
> +    from ovos_skills_manager.skill_entry import SkillEntry
This could definitely be a static class method there. No objections here; I can relocate and refactor the name to include 'github' for clarity. Should it be an internal method for `OVOSSkillsManager`?

2021-06-11 22:22 UTC, JarbasAl commented on ovos_skills_manager/github/utils.py
> +    from ovos_skills_manager.skill_entry import SkillEntry
maybe just call it `install_from_url` and make it a static method in base class yes, that should get rid of the cyclic imports

2021-06-12 19:03 UTC, ChanceNCounter requested changes
Review may not be complete, but let's call that a round.

2021-06-12 19:04 UTC, ChanceNCounter commented on ovos_skills_manager/osm.py
> +    def skill_entry_from_url(url: str):
(I get that you guys decided to move the import directly to `osm`, I just don't think that necessarily means the code itself has to live there)

2021-06-14 16:11 UTC, NeonDaniel commented on ovos_skills_manager/osm.py
> +    def skill_entry_from_url(url: str):
This naming is redundant now that it is in OSM, though I'm not sure we want that symmetry with `from_json` since this doesn't make a "complete" skill entry; just enough to install. I almost want to mark this method as private since it is only useful for installing via URL.

2021-06-14 16:15 UTC, NeonDaniel commented on ovos_skills_manager/github/utils.py
>  from ovos_skills_manager.exceptions import *
I think it makes sense logically to import all the exceptions for readability and for tooltips as util methods are added later..

2021-06-14 16:18 UTC, NeonDaniel commented on tests/test_osm.py
> +    def test_get_skill_entry_from_url_default_branch(self):
That would require another test skill repo; in general I think that would be a good idea though to test things like no releases, different default branches, etc.

2021-06-18 01:15 UTC, ChanceNCounter approved these changes

2021-06-18 01:16 UTC, merged