handle some missing fields
OpenVoiceOS/ovos_skill_manager pull request #63
Opened 2021-09-03 05:29 UTC by JarbasAl

SkillEntry should populate some missing fields . Fixes some exceptions surrounding skills descriptions etc when splitting None

2021-09-03 17:14 UTC, NeonDaniel requested changes

2021-09-03 17:14 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +    def appstore(self)  :
Accidental whitespace inserted?

2021-09-03 17:14 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +        author, repo = author_repo_from_github_url(self.url)
I think the URL parsing here should be in a try/except in case the author and repo can't be parsed from the URL.

2021-09-03 17:14 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
In markdown, the `\n` might not be an intentional newline since it isn't rendered as a newline; should this be `\n\n` or `.`?

2021-09-03 17:14 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +        author, repo = author_repo_from_github_url(self.url)
I think the URL parsing here should be in a try/except in case the author and repo can't be parsed from the URL.

2021-09-03 17:14 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +        author, repo = author_repo_from_github_url(self.url)
I think the URL parsing here should be in a try/except in case the author and repo can't be parsed from the URL.

2021-09-03 17:32 UTC, JarbasAl commented on ovos_skills_manager/skill_entry.py
> +        author, repo = author_repo_from_github_url(self.url)
does that ever happen? i dont think its possible for that to fail

and if the url is invalid we need to catch that way way earlier

2021-09-03 18:23 UTC, JarbasAl commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
`.` is dangerous as it can be an acronym, i think `\n` is fine, this will never be perfect but the important is to not get a lot of text. test the osm skill with one of the neon skills, you cant read anything at all... idk if it was alerts or caffeine wiz that made me revist this, but it was so much text that it was unreadable. but we could consider this a UI bug i guess...

can also look into using quebra_frases if we want to do it properly https://github.com/OpenJarbas/quebra_frases

2021-09-05 05:10 UTC, ChanceNCounter commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
Why not `splitlines`?

2021-09-20 17:40 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
How does `splitlines` handle markdown? I guess that, as Jarbas noted, this is fallback behavior anyways so it may not be worth much extra dev work

2021-09-20 17:44 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +        author, repo = author_repo_from_github_url(self.url)
I'm mostly thinking for the future if we want to build a SkillEntry for a local skill with no URL defined. I can accept this as out of scope for now though

2021-09-29 23:59 UTC, ChanceNCounter commented on ovos_skills_manager/skill_entry.py
> +        author, repo = author_repo_from_github_url(self.url)
I've handled this by rearranging the logic in the various funcs that do this. `return_val = json.get()` and then `if self.url and not return_val: author, repo = ...`

2021-09-30 00:02 UTC, ChanceNCounter commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
Slapping a TODO in there to consider quebra_frases or a more nuanced approach, but +1 not worth much dev time at this juncture

2021-09-30 00:04 UTC, ChanceNCounter approved these changes

2021-09-30 19:25 UTC, ChanceNCounter commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
I just realized this can still blow up when `skill_description()` returns something nullish. Thoughts?

2021-10-01 23:57 UTC, NeonDaniel commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
add `if self.skill_description else ""`? and/or make `self.skill_description` return a string always?

2021-10-02 14:41 UTC, ChanceNCounter commented on ovos_skills_manager/skill_entry.py
> +               self.skill_description.split("\n")[0]
Indeed, I think I left a local branch that way. Will push ASAP.

2021-10-04 21:20 UTC, NeonDaniel approved these changes

2021-10-05 01:03 UTC, merged